### ISSUE TITLE
Создание карточного тренажера

### ISSUE THREAD

**Issue by egormm** [gurovic/veng#1]
Разобраться в GITHUB'е и переписать скриптик с питон 2.7
http://habrahabr.ru/post/211466/

**Comment by egormm** [comment]
import sys
import random

def keysToValues(dic):
    wrong = 0
    right = 0
    keys = dic.keys()
    while True:
        tmpkey = random.choice(keys)
        print("{0}: {1}".format(len(keys), tmpkey))
        #print str(len(keys))+":", tmpkey
        value = dic[tmpkey]
        #answ = input("Translation: ")
        if input("Translation: ") in value.split(", "):
            print("True. {0}\n".format(value)) #fjf
            right += 1
            keys.remove(tmpkey)
        else:
            wrong += 1
            print("Wrong! {0}\n".format(value))
        if len(keys) < 1:
            input("\n\nNothing\nRight - {0}. Wrong - {1}".format(right, wrong))
            sys.exit()

def main():
    try:
        wordict = eval(open(sys.argv[1]).read())
    except:
        print("You have to enter all parameters.\nExample: python wordrepeater.py yourdictionary.json")
        input("")
    mode = input("Choose mode:\n\t1:Word To Translation;\n\t2:Translation To Word.\n>> ");
    if mode == "2": wordict = {wordict[k]:k for k in wordict.keys()}
    elif mode == "":
        print("Exit")
        sys.exit()

```
keysToValues(wordict)
```

if **name** == "**main**":
    main()

**Comment by egormm** [comment]
http://pastebin.ru/NnI84d2x

**Comment by gurovic** [comment]
Кто-то не разобрался в гитхабе(
